dbt_project:
  outputs:
    dev:
      dataset: transformed_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/alejandrogonzalezbueno/Projects/bigquery/civ-dev-dataengineering-8c6359b2eb7f.json
      location: europe-southwest1
      method: service-account
      priority: interactive
      project: civ-dev-dataengineering
      threads: 1
      type: bigquery
  target: dev